server:
  port: 8082

spring:
  application:
    name: shipping

  profiles:
    active: local

  kafka:
    consumer:
      group-id: shipping
      value-deserializer: com.ngoctuan.shipping.events.ShipmentDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

    listener:
      ack-mode: MANUAL
      missing-topics-fatal: false

logging.level.org.springframework.boot.actuate.trace.WebRequestTraceFilter: TRACE
