server:
  port: 8082

spring:
  application:
    name: shipping

  kafka:
    consumer:
      group-id: shipping
      value-deserializer: com.ngoctuan.shipping.events.ShipmentDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

    listener:
      ack-mode: MANUAL
      missing-topics-fatal: false

  jpa:
    hibernate.ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 081199th
    driver-class-name: org.postgresql.Driver

logging.level.org.springframework.boot.actuate.trace.WebRequestTraceFilter: TRACE
