server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: secret_key_for_my_personal_e_commerce_project