networks:
  myNetwork:

services:

  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=081199th
    networks:
      - myNetwork

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=081199th
    networks:
      - myNetwork

  kafka:
      image: 'apache/kafka:latest'
      ports:
        - '9092:9092'
      networks:
        - myNetwork
