server:
  port: 8080

spring:
  application:
    name: order

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    listener:
      missing-topics-fatal: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 081199th
    driver-class-name: org.postgresql.Driver

logging.level.com.ngoctuan.order.clients: TRACE
logging.level.org.springframework.boot.actuate.trace.WebRequestTraceFilter: TRACE
