server:
  port: 8080

spring:
  application:
    name: order

  profiles:
    active: local

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    listener:
      missing-topics-fatal: false

logging.level.com.ngoctuan.order.clients: TRACE
logging.level.org.springframework.boot.actuate.trace.WebRequestTraceFilter: TRACE
