server:
  port: 8084

spring:
  application:
    name: invoice

  profiles:
    active: local

  kafka:
    consumer:
      group-id: invoicing
      value-deserializer: com.ngoctuan.invoice.events.InvoiceDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

    listener:
      ack-mode: MANUAL
      missing-topics-fatal: false

logging.level.org.springframework.boot.actuate.trace.WebRequestTraceFilter: TRACE
